pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/thxmohamed/Tingeso']])
                dir("frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Verify Docker") {
            steps {
                script {
                    bat "docker ps" // 
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t thxmohamed/frontend-container ."
                            bat "docker push thxmohamed/frontend-container"
                        }
                    }                    
                }
            }
        }
    }
}