pipeline {
    agent any
    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(branches: [[name: '*/main']], 
                                userRemoteConfigs: [[url: 'https://github.com/thxmohamed/Tingeso']])
                dir("frontend") {
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Verify Docker") {
            steps {
                script {
                    bat "docker ps"
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                dir("frontend") {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                            bat 'docker login -u "%DOCKER_USERNAME%" -p "%DOCKER_PASSWORD%" https://index.docker.io/v1/'
                            bat "docker build -t thxmohamed/frontend-container ."
                            bat "docker push thxmohamed/frontend-container"
                        }
                    }
                }
            }
        }
    }
}
