pipeline {
    agent any
    tools {
        maven "maven"
    }
    stages {
        stage("Clone Repository") {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                                userRemoteConfigs: [[url: 'https://github.com/thxmohamed/Tingeso']])
            }
        }

        stage("Build JAR File") {
            steps {
                dir("backend") {
                    bat "mvn clean package"
                }
            }
        }

        stage("Test") {
            steps {
                dir("backend") {
                    bat "mvn test"
                }
            }
        }

        stage("Build and Push Docker Image") {
            steps {
                dir("backend") {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                            bat 'docker login -u "%DOCKER_USERNAME%" -p "%DOCKER_PASSWORD%" https://index.docker.io/v1/'
                            bat "docker build -t thxmohamed/backend-container ."
                            bat "docker push thxmohamed/backend-container"
                        }
                    }
                }
            }
        }
    }
}
